<?php 
// $Id: feeds_youtube.module,v 1.4 2011/01/31 22:57:28 wojtha Exp $

/**
 * @file
 * Adds a Youtube feed processor to the Feeds module.
 */

/**
 * Implements ctools_plugin_api().
 */

function feeds_youtube_ctools_plugin_api($owner, $api) {
  if ($owner == 'feeds' && $api == 'plugins') {
    return array('version' => 1);
  }
}

/**
 * Implements hook_feeds_plugins().
 */
function feeds_youtube_feeds_plugins() {
  $info = array();
  $info['FeedsYoutubeParser'] = array(
    'name' => 'Youtube parser',
    'description' => 'Parse Youtube feeds.',
    'help' => 'Use PHP SimpleXML parser to parse Youtube feeds.',
    'handler' => array(
      'parent' => 'FeedsParser',
      'class' => 'FeedsYoutubeParser',
      'file' => 'FeedsYoutubeParser.inc',
      'path' => drupal_get_path('module', 'feeds_youtube'),
    ),
  );
  return $info;
}
