<?php
function feeds_youtube_fetcher_feeds_plugins() {
  $info = array();
  $info['YouTubeFetcher'] = array(
    'name' => 'YouTube Playlist Fetcher',
    'description' => 'Fetches a YouTube playlist using pagination.',
    'help' => 'Fetches a YouTube playlist using pagination.',
    'handler' => array(
      'parent' => 'FeedsHTTPFetcher',
      'class' => 'YouTubeFetcher',
      'file' => 'YouTubeFetcher.inc',
      'path' => drupal_get_path('module', 'feeds_youtube_fetcher'),
    ),
  );
  return $info;
}
