<?php
/**
 * Implement hook_install().
 *
 * Perform actions to set up the site for this profile.
 */
function relay_install() {
  include_once DRUPAL_ROOT . '/profiles/standard/standard.install';
  standard_install();
  
  db_update('system')
  ->fields(array('status' => 1))
  ->condition('type', 'theme')
  ->condition('name', 'relay')
  ->execute();
  variable_set('theme_default', 'relay');
}
?>